name: CI/CD Pipeline
on:
    push:
        branches: 
            - main
permissions:
    contents: read
    packages: write

jobs:
    build-image:
        environment: production
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: |
                    ghcr.io/astro-ez/quran-recite-app
                tags: |
                    type=schedule
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=semver,pattern={{major}}
                    type=sha

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v1
            
            - name: Login to Github Container registry
              if: ${{github.event_name != 'pull_request'}}
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                platforms: linux/amd64
                push: ${{github.event_name != 'pull_request'}}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha, mode=max
              


